### ISSUE TITLE
SIgn up in the ICLR 2019 reproducibility challenge

### ISSUE THREAD

**Issue by xavigiro** [telecombcn-dl/2018-dlai-team1#1]
You should sign up as soon as possible to the [ICLR 2019 reproducibility challenge](https://reproducibility-challenge.github.io/iclr_2019/) and claim the PA-GAN paper. You need to fill [this form](https://docs.google.com/forms/d/e/1FAIpQLSehp6-IcArs4hzWB9gkPsR_abekpZrDXCGf27I5G4vZ5h1kFQ/viewform) to sign up.

When you fill it, have Dani as the team leader (first author) and also include the list of authors. I suggest I am the last one, and Noé the previous one. Something like:

Dani Fojo, Janna Escur, Miquel Tubau, Paula Gomez, Noe Casas and Xavier Giro-i-Nieto

The order of authors between positions 2-4 could be any, as much as I know. I chose a solution that would alternate genders, but any other criterion you agree would also work as well.

In affiliation, write "Universitat Politecnica de Catalunya".

E-mail addresses for Noe and me are noe.casas@upc.edu & xavier.giro@upc.edu.

Notice that you can request for extra credit on GCloud once you have signed up. Please let me konw once you have signed up.

**Comment by jannaescur** [comment]
Thanks Xavi for the information. We have already signed up: https://github.com/reproducibility-challenge/iclr_2019/issues/87
